<section class="bg-acceuil">
    <div class="flex flex-col mx-auto text-center md:max-[55rem]">
        <div class="bg-white mx-auto rounded-lg shadow dark:border md:w-[55rem] md:mt-0 xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <button class="py-3 px-5 flex ml-auto text-sm font-medium text-white rounded-lg bg-gray-400 sm:w-fit hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
                <a href="/assets/pdf/CGU.pdf" target="_blank">Télécharger</a>
                </button>

                <h1 class="text-3xl my-4 text-gray-700 dark:text-gray-200">Condition générales d'utilisation <span class="text-green-600">Tea'</span><span class="text-amber-700">Coffee</span></h1>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">En vigueur au 03/04/2024</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Les présentes conditions générales d'utilisation (dites « CGU ») ont pour objet l'encadrement juridique des modalités de mise à disposition du site et des services par Tea'Coffee et de définir les conditions d’accès et d’utilisation des services par « l'Utilisateur ».</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Les présentes CGU sont accessibles sur le site à la rubrique «CGU».</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Toute inscription ou utilisation du site implique l'acceptation sans aucune réserve ni restriction des présentes CGU par l’utilisateur. Lors de l'inscription sur le site via le Formulaire d’inscription, chaque utilisateur accepte expressément les présentes CGU en cochant la case précédant le texte suivant : « Je reconnais avoir lu et compris les CGU et je les accepte ».</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">En cas de non-acceptation des CGU stipulées dans le présent contrat, l'Utilisateur se doit de renoncer à l'accès des services proposés par le site.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Avenue Franklin la tortue, 83000 Toulon se réserve le droit de modifier unilatéralement et à tout moment le contenu des présentes CGU.</p>

                <h2 class="text-2xl mt-20 text-gray-700 dark:text-gray-200 mb-4">ARTICLE 1 : LES MENTIONS LÉGALES</h2>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">L'édition du site Avenue Franklin la tortue, 83000 Toulon est assurée par la Société Projet étudiant Tea'Coffee au capital de 0 euros, immatriculée au RCS de _______________ sous le numéro _______________, dont le siège social est situé au _______________ Numéro de téléphone 00000000 Adresse e-mail : _______________.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Le Directeur de la publication est : _______________ L'hébergeur du site Avenue Franklin la tortue, 83000 Toulon est la société Plesk, dont le siège social est situé au _______________, avec le numéro de téléphone : _______________.</p>

                <h2 class="text-2xl mt-20 text-gray-700 dark:text-gray-200 mb-4">ARTICLE 2 : ACCÈS AU SITE</h2>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Le site Avenue Franklin la tortue, 83000 Toulon permet à l'Utilisateur un accès gratuit aux services suivants : Le site internet propose les services suivants : Projet étudiant de boutique en ligne Le site est accessible gratuitement en tout lieu à tout Utilisateur ayant un accès à Internet. Tous les frais supportés par l'Utilisateur pour accéder au service (matériel informatique, logiciels, connexion Internet, etc.) sont à sa charge.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">L’Utilisateur non membre n'a pas accès aux services réservés. Pour cela, il doit s’inscrire en remplissant le formulaire. En acceptant de s’inscrire aux services réservés, l’Utilisateur membre s’engage à fournir des informations sincères et exactes concernant son état civil et ses coordonnées, notamment son adresse email.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Pour accéder aux services, l’Utilisateur doit ensuite s'identifier à l'aide de son identifiant et de son mot de passe qui lui seront communiqués après son inscription.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Tout Utilisateur membre régulièrement inscrit pourra également solliciter sa désinscription en se rendant à la page dédiée sur son espace personnel. Celle-ci sera effective dans un délai raisonnable.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Tout événement dû à un cas de force majeure ayant pour conséquence un dysfonctionnement du site ou serveur et sous réserve de toute interruption ou modification en cas de maintenance, n'engage pas la responsabilité de Avenue Franklin la tortue, 83000 Toulon. Dans ces cas, l’Utilisateur accepte ainsi ne pas tenir rigueur à l’éditeur de toute interruption ou suspension de service, même sans préavis.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">L'Utilisateur a la possibilité de contacter le site par messagerie électronique à l’adresse email de l’éditeur communiqué à l’ARTICLE 1.</p>

                <h2 class="text-2xl mt-20 text-gray-700 dark:text-gray-200 mb-4">ARTICLE 3 : COLLECTE DES DONNÉES</h2>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Le site assure à l'Utilisateur une collecte et un traitement d'informations personnelles dans le respect de la vie privée conformément à la loi n°78-17 du 6 janvier 1978 relative à l'informatique, aux fichiers et aux libertés.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">En vertu de la loi Informatique et Libertés, en date du 6 janvier 1978, l'Utilisateur dispose d'un droit d'accès, de rectification, de suppression et d'opposition de ses données personnelles. L'Utilisateur exerce ce droit :</p>
                <ul>
                <li>via un formulaire de contact ;</li>
                </ul>

                <h2 class="text-2xl mt-20 text-gray-700 dark:text-gray-200 mb-4">ARTICLE 4 : PROPRIÉTÉ INTELLECTUELLE</h2>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Les marques, logos, signes ainsi que tous les contenus du site (textes, images, son…) font l'objet d'une protection par le Code de la propriété intellectuelle et plus particulièrement par le droit d'auteur. La marque Tea'Coffee est une marque déposée par Projet étudiant.Toute représentation et/ou reproduction et/ou exploitation partielle ou totale de cette marque, de quelque nature que ce soit, est totalement prohibée.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">L'Utilisateur doit solliciter l'autorisation préalable du site pour toute reproduction, publication, copie des différents contenus. Il s'engage à une utilisation des contenus du site dans un cadre strictement privé, toute utilisation à des fins commerciales et publicitaires est strictement interdite.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Toute représentation totale ou partielle de ce site par quelque procédé que ce soit, sans l’autorisation expresse de l’exploitant du site Internet constituerait une contrefaçon sanctionnée par l’article L 335-2 et suivants du Code de la propriété intellectuelle.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Il est rappelé conformément à l’article L122-5 du Code de propriété intellectuelle que l’Utilisateur qui reproduit, copie ou publie le contenu protégé doit citer l’auteur et sa source.</p>

                <!-- Le reste du texte a également été balisé, mais pour des raisons de longueur, je ne l'ai pas inclus ici -->

                <h2 class="text-2xl mt-20 text-gray-700 dark:text-gray-200 mb-4">ARTICLE 5 : RESPONSABILITÉ</h2>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Les sources des informations diffusées sur le site Avenue Franklin la tortue, 83000 Toulon sont réputées fiables mais le site ne garantit pas qu’il soit exempt de défauts, d’erreurs ou d’omissions. Les informations communiquées sont présentées à titre indicatif et général sans valeur contractuelle.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Malgré des mises à jour régulières, le site Avenue Franklin la tortue, 83000 Toulon ne peut être tenu responsable de la modification des dispositions administratives et juridiques survenant après la publication. De même, le site ne peut être tenue responsable de l’utilisation et de l’interprétation de l’information contenue dans ce site.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">L'Utilisateur s'assure de garder son mot de passe secret. Toute divulgation du mot de passe, quelle que soit sa forme, est interdite. Il assume les risques liés à l'utilisation de son identifiant et mot de passe. Le site décline toute responsabilité.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Le site Avenue Franklin la tortue, 83000 Toulon ne peut être tenu pour responsable d’éventuels virus qui pourraient infecter l’ordinateur ou tout matériel informatique de l’Internaute, suite à une utilisation, à l’accès, ou au téléchargement provenant de ce site.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">La responsabilité du site ne peut être engagée en cas de force majeure ou du fait imprévisible et insurmontable d'un tiers.</p>

                <h2 class="text-2xl mt-20 text-gray-700 dark:text-gray-200 mb-4">ARTICLE 6 : LIENS HYPERTEXTES</h2>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Des liens hypertextes peuvent être présents sur le site. L’Utilisateur est informé qu’en cliquant sur ces liens, il sortira du site Avenue Franklin la tortue, 83000 Toulon. Ce dernier n’a pas de contrôle sur les pages web sur lesquelles aboutissent ces liens et ne saurait, en aucun cas, être responsable de leur contenu.</p>

                <h2 class="text-2xl mt-20 text-gray-700 dark:text-gray-200 mb-4">ARTICLE 7 : COOKIES</h2>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">L’Utilisateur est informé que lors de ses visites sur le site, un cookie peut s’installer automatiquement sur son logiciel de navigation.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Les cookies sont de petits fichiers stockés temporairement sur le disque dur de l’ordinateur de l’Utilisateur par votre navigateur et qui sont nécessaires à l’utilisation du site Avenue Franklin la tortue, 83000 Toulon. Les cookies ne contiennent pas d’information personnelle et ne peuvent pas être utilisés pour identifier quelqu’un. Un cookie contient un identifiant unique, généré aléatoirement et donc anonyme. Certains cookies expirent à la fin de la visite de l’Utilisateur, d’autres restent.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">L’information contenue dans les cookies est utilisée pour améliorer le site Avenue Franklin la tortue, 83000 Toulon.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">En naviguant sur le site, L’Utilisateur les accepte.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">L’Utilisateur doit toutefois donner son consentement quant à l’utilisation de certains cookies.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">A défaut d’acceptation, l’Utilisateur est informé que certaines fonctionnalités ou pages risquent de lui être refusées.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">L’Utilisateur pourra désactiver ces cookies par l’intermédiaire des paramètres figurant au sein de son logiciel de navigation.</p>

                <h2 class="text-2xl mt-20 text-gray-700 dark:text-gray-200 mb-4">ARTICLE 8 : PUBLICATION PAR L’UTILISATEUR</h2>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">Le site permet aux membres de publier les contenus suivants : Commentaire. Dans ses publications, le membre s’engage à respecter les règles de la Netiquette (règles de bonne conduite de l’internet) et les règles de droit en vigueur. Le site peut exercer une modération sur les publications et se réserve le droit de refuser leur mise en ligne, sans avoir à s’en justifier auprès du membre. Le membre reste titulaire de l’intégralité de ses droits de propriété intellectuelle. Mais en publiant une publication sur le site, il cède à la société éditrice le droit non exclusif et gratuit de représenter, reproduire, adapter, modifier, diffuser et distribuer sa publication, directement ou par un tiers autorisé, dans le monde entier, sur tout support (numérique ou physique), pour la durée de la propriété intellectuelle. Le Membre cède notamment le droit d'utiliser sa publication sur internet et sur les réseaux de téléphonie mobile. La société éditrice s'engage à faire figurer le nom du membre à proximité de chaque utilisation de sa publication. Tout contenu mis en ligne par l'Utilisateur est de sa seule responsabilité. L'Utilisateur s'engage à ne pas mettre en ligne de contenus pouvant porter atteinte aux intérêts de tierces personnes. Tout recours en justice engagé par un tiers lésé contre le site sera pris en charge par l'Utilisateur. Le contenu de l'Utilisateur peut être à tout moment et pour n'importe quelle raison supprimé ou modifié par le site, sans préavis.</p>

                <h2 class="text-2xl mt-20 text-gray-700 dark:text-gray-200 mb-4">ARTICLE 9 : DROIT APPLICABLE ET JURIDICTION COMPÉTENTE</h2>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">La législation française s'applique au présent contrat. En cas d'absence de résolution amiable d'un litige né entre les parties, les tribunaux français seront seuls compétents pour en connaître. Pour toute question relative à l’application des présentes CGU, vous pouvez joindre l’éditeur aux coordonnées inscrites à l’ARTICLE 1.</p>
                <p class="text-start mx-20 text-gray-700 dark:text-gray-200 text-sm">CGU réalisées sur <a href="https://legalplace.fr/">https://legalplace.fr/</a></p>


            </div>
        </div>
    </div>
</section>
