version: "3.8"

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: /run/secrets/databaseMYSL
      MYSQL_USER: /run/secrets/userMYSQL
      MYSQL_PASSWORD: /run/secrets/passwordMYSQL
      MYSQL_ROOT_PASSWORD: /run/secrets/passwordRootMYSQL
    container_name: data_center_mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-data/dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  nginx:
    build: ./docker-data/images/nginx/
    restart: always
    volumes:
      - nginx_conf:/etc/nginx/
      - ./backend-php:/www
      - ./docker-data/nginx_conf:/etc/nginx/conf.d
      - ./docker-data/php_conf/ini:/usr/local/etc/php/conf.d
    # Port ajouté
    ports:
      - "8880:80"
      # Port 81 mappé
      - "8881:81"

  php:
    depends_on:
      - db
    hostname: boutique-js.dok
    restart: always
    build:
      context: ./backend-php
      dockerfile: Dockerfile
    volumes:
      - ./backend-php:/www
    links:
      - db:db

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "7779:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_PASSWORD: /run/secrets/passwordMYSQL
      PMA_USER: /run/secrets/userMYSQL
      PMA_PORTS: /run/secrets/portPMA1|/run/secrets/portPMA2
    links:
      - db:db

  node:
    hostname: api.boutique-js.dok
    restart: always
    build:
      context: ./nodeexpress
      dockerfile: Dockerfile
    volumes:
      - ./nodeexpress:/www

volumes:
  db_data:
    name: data_center_db_data
  nginx_conf:
