version: "3.8"

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_USER_FILE: /run/secrets/user_mysql
      MYSQL_PASSWORD_FILE: /run/secrets/password_mysql
      MYSQL_DATABASE_FILE: /run/secrets/database_mysql
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/password_root_mysql
      MYSQL_TCP_PORT: 55055
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-data/dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    secrets:
      - password_mysql
      - user_mysql
      - database_mysql
      - password_root_mysql

  nginx:
    build: ./docker-data/images/nginx/
    restart: always
    volumes:
      - nginx_conf:/etc/nginx/
      - ./backend-php:/www
      - ./docker-data/nginx_conf:/etc/nginx/conf.d
      - ./docker-data/php_conf/ini:/usr/local/etc/php/conf.d
    # Port ajouté
    ports:
      # Port 80 mappé backend-php
      - "8880:80"
      # Port 81 mappé node-service
      - "8881:81"
      # Port 82 mappé node-jwt
      - "8882:82"

  php:
    depends_on:
      - db
    hostname: teacoffee.dock
    restart: always
    secrets:
      - api_key_stripe
      - database_mysql
      - user_mysql
      - password_root_mysql
      - password_mysql
      - port_mysql
      - dsn_mysql
      - host_mysql
      - charset_mysql
    build:
      context: ./backend-php
      dockerfile: Dockerfile
    volumes:
      - ./backend-php:/www
    links:
      - db:db

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "7779:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_ROOT_PASSWORD_FILE: /run/secrets/password_root_mysql
      PMA_PORT: 55055
    secrets:
      - password_root_mysql
    links:
      - db:db

  node:
    hostname: teacoffee.dock
    restart: always
    secrets:
      - api_key_stripe
    build:
      context: ./node-service
      dockerfile: Dockerfile
    volumes:
      - ./node-service:/www

  node-jwt:
    hostname: teacoffee.dock
    restart: always
    secrets:
      - jwt_key
    build:
      context: ./node-jwt
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./node-jwt:/app

secrets:
  jwt_key:
    file: ./docker-data/secrets/jwt_key.txt
  api_key_stripe:
    file: ./docker-data/secrets/api_key_stripe.txt
  database_mysql:
    file: ./docker-data/secrets/database_mysql.txt
  password_mysql:
    file: ./docker-data/secrets/password_mysql.txt
  password_root_mysql:
    file: ./docker-data/secrets/password_root_mysql.txt
  user_mysql:
    file: ./docker-data/secrets/user_mysql.txt
  port_mysql:
    file: ./docker-data/secrets/port_mysql.txt
  dsn_mysql:
    file: ./docker-data/secrets/dsn_mysql.txt
  host_mysql:
    file: ./docker-data/secrets/host_mysql.txt
  charset_mysql:
    file: ./docker-data/secrets/charset_mysql.txt

volumes:
  db_data:
  nginx_conf:
