-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 10:24:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema teacoffee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teacoffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teacoffee` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema teacoffee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teacoffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teacoffee` DEFAULT CHARACTER SET utf8mb4 ;
USE `teacoffee` ;

-- -----------------------------------------------------
-- Table `teacoffee`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`category` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `description` VARCHAR(1000) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teacoffee`.`sub_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`sub_category` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`sub_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sub_category_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_sub_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `teacoffee`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teacoffee`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`products` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`products` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `id_charac` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `category_id` INT NOT NULL,
  `sub_category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_product_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_products_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_products_sub_category1_idx` (`sub_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `teacoffee`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_sub_category1`
    FOREIGN KEY (`sub_category_id`)
    REFERENCES `teacoffee`.`sub_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teacoffee`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`images` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image_main` TINYINT NULL,
  `url_image` TEXT(500) NULL,
  `products_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `teacoffee`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teacoffee`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`users` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`users` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `email` VARCHAR(75) CHARACTER SET 'utf8mb4' NOT NULL,
  `password` VARCHAR(155) CHARACTER SET 'utf8mb4' NOT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `adress` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `role` ENUM('user', 'admin') CHARACTER SET 'utf8mb4' NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teacoffee`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`orders` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`orders` (
  `id` INT NOT NULL,
  `id_product` INT NULL DEFAULT NULL,
  `basket` TINYINT(1) NULL DEFAULT NULL,
  `status` ENUM('en attente', 'expedier', 'livrer', 'echec') CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `teacoffee`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '		';


-- -----------------------------------------------------
-- Table `teacoffee`.`ProductOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`ProductOrder` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`ProductOrder` (
  `products_id` INT UNSIGNED NOT NULL,
  `orders_id` INT NOT NULL,
  INDEX `fk_ProductOrder_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_ProductOrder_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_ProductOrder_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `teacoffee`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductOrder_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `teacoffee`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `teacoffee`.`charac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`charac` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`charac` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` ENUM('kg', 'g', 'm', 'cm', 'country', 'color', 'amper', 'kelvin', 'wats', 'volts', 'celsius', 'ohm', 'byte', 'gigabyte', 'megabyte', 'm2', 'dolar', 'eu', 'livre', 'cal', 'kmh', 'day', 'week', 'year', 'month', 'hertz', 'percent', 'pixel', 'decibel', 'l', 'cl', 'ml') NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `teacoffee`.`productsCharac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`productsCharac` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`productsCharac` (
  `value` VARCHAR(255) NULL,
  `products_id` INT UNSIGNED NOT NULL,
  `charac_id` INT NOT NULL,
  INDEX `fk_productsCharac_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_productsCharac_charac1_idx` (`charac_id` ASC) VISIBLE,
  CONSTRAINT `fk_productsCharac_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `teacoffee`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productsCharac_charac1`
    FOREIGN KEY (`charac_id`)
    REFERENCES `teacoffee`.`charac` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teacoffee`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`ratings` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NULL,
  `products_id` INT UNSIGNED NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ratings_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_ratings_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_ratings_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `teacoffee`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `teacoffee`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teacoffee`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teacoffee`.`comments` ;

CREATE TABLE IF NOT EXISTS `teacoffee`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT(500) NULL,
  `users_id` INT NOT NULL,
  `products_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_comments_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `teacoffee`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `teacoffee`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `teacoffee` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
